version: '2.4'

networks:
  test:
    name: fabric_solar_project

services:

  ca_company_a:
    image: hyperledger/fabric-ca:1.5.1
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-company-a
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --cfg.affiliations.allowremove  --cfg.identities.allowremove'

    volumes:
      - ../organizations/fabric-ca/companyA:/etc/hyperledger/fabric-ca-server
    container_name: ca_company_a
    networks:
      - test
      
  ca_company_b:
      image: hyperledger/fabric-ca:1.5.1
      labels:
        service: hyperledger-fabric
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca-company-b
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=8054
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
      ports:
        - "8054:8054"
        - "18054:18054"
      command: sh -c 'fabric-ca-server start -b admin:adminpw -d --cfg.affiliations.allowremove  --cfg.identities.allowremove'

      volumes:
        - ../organizations/fabric-ca/companyB:/etc/hyperledger/fabric-ca-server
      container_name: ca_company_b
      networks:
        - test


  ca_comprador:
      image: hyperledger/fabric-ca:1.5.1
      labels:
        service: hyperledger-fabric
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca-comprador
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=10054
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:10754
      ports:
        - "10054:10054"
        - "10754:10754"
      command: sh -c 'fabric-ca-server start -b admin:adminpw -d --cfg.affiliations.allowremove  --cfg.identities.allowremove'

      volumes:
        - ../organizations/fabric-ca/companyComprador:/etc/hyperledger/fabric-ca-server
      container_name: ca_comprador
      networks:
        - test
  

  ca_orderer:
      image: hyperledger/fabric-ca:1.5.1
      labels:
        service: hyperledger-fabric
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca-orderer
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=9054
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
      ports:
        - "9054:9054"
        - "19054:19054"
      command: sh -c 'fabric-ca-server start -b admin:adminpw -d --cfg.affiliations.allowremove  --cfg.identities.allowremove'
      volumes:
        - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
      container_name: ca_orderer
      networks:
        - test
